* #networking, #arhictecture
* Scalability
Compared to ~client-server~ paradigm architecture the ~P2P~ has an innate capacity to scale.
When a new end-point is connect to the network the network scale!
* Each host in the P2P paradigm is equipotent, there is no central server,  the book ( [[Computer Networking a Top Down Approach]] ) show an interesting example on a file  sharing application with [[Client-Server]] and P2P.
:PROPERTIES:
:id: 637e966c-6342-4c3c-92c4-eae528607c04
:END:
* Type of P2P
** P2P  Pure
no central server, each peer have the same role.
** P2P with Discovery Server
Self explanatory.
On a new connection from a new peer it give to the new user a list of the other users.
** P2P with Discovery and Lookup Server
Like the previous but there is another host, the Lookup Server, it is also connect to the network (hence also known by the Discovery Server).
The Lookup Server send the a list with all the contents at regular intervals to all the client, this is used to optimize the network.